server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # Archivos estáticos (JS, CSS, imágenes, fuentes, Leaflet icons incluidos)
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)$ {
        try_files $uri =404;
        access_log off;
        expires 1y;
        add_header Cache-Control "public";
    }

    # SPA Angular
    location / {
        try_files $uri $uri/ /index.html;
    }
}
